Implementation of LASER to the corpus

In [224]:
# Imports
import numpy as np
from scipy import spatial
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split, KFold
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

from keras import models
from keras import layers
import keras

Load Dataset

In [113]:
df1 = pd.read_csv("scores.csv")

In [114]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21704 entries, 0 to 21703
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   source       21704 non-null  object 
 1   reference    21704 non-null  object 
 2   translation  21704 non-null  object 
 3   z-score      21704 non-null  float64
 4   avg-score    21704 non-null  float64
 5   annotators   21704 non-null  int64  
dtypes: float64(2), int64(1), object(3)
memory usage: 1017.5+ KB


In [115]:
df1.head()

source  \
0  Ihr Zeitlupentempo maßen sie, als sie vor Spit...   
1  Er sagte, dass die Bereiche ruhige Treffpunkte...   
2  Für die Geschäftsleute an der B 27 ist es nur ...   
3  Diese Fähigkeit sei möglicherweise angeboren o...   
4  Weil sie Wassertemperaturen um die sechs Grad ...   

                                           reference  \
0  Her timeless pace measures them when they equi...   
1  He said the areas offer quiet meeting points b...   
2  For businessmen at the B 27, it's only a small...   
3  This ability may be born or developed with gen...   
4  Because they prefer water temperatures around ...   

                                         translation   z-score  avg-score  \
0  Their slow speed was measured by researchers o... -0.345024       76.0   
1  He said the spaces provided calm meeting point...  0.903800       97.5   
2  This is only a small consolation for businesse...  0.700503       94.0   
3  This ability may be innate, or may develop as ... -1.256572       51.5   
4  They generally only come to the surface in win...  0.293909       87.0   

   annotators  
0           1  
1           2  
2           1  
3           2  
4           2

Comparison of LASER embeddings

In [116]:
source_arr = np.load("laser.source_embeds.npy")
refer_arr = np.load("laser.reference_embeds.npy")
trans_arr = np.load("laser.translation_embeds.npy")

Cosine Similarity

In [160]:
cos_similarity_ref_hyp = []
cos_similarity_src_ref = []
cos_similarity_src_hyp = []

# for each of the cos similarity, put them into lists.
for i in range(refer_arr.shape[0]):
    cos_similarity_ref_hyp.append((spatial.distance.cosine(refer_arr[i],trans_arr[i])*-1)+1)
    cos_similarity_src_ref.append((spatial.distance.cosine(source_arr[i],refer_arr[i])*-1)+1)
    cos_similarity_src_hyp.append((spatial.distance.cosine(source_arr[i],trans_arr[i])*-1)+1)


# Standardize and transform into series.
scaler = StandardScaler()
cs_rh = pd.Series(scaler.fit_transform(np.array(cos_similarity_ref_hyp).reshape(-1,1)).flatten(),name="cos_sim_ref_hyp")
cs_sr = pd.Series(scaler.fit_transform(np.array(cos_similarity_src_ref).reshape(-1,1)).flatten(),name="cos_sim_src_ref")
cs_sh = pd.Series(scaler.fit_transform(np.array(cos_similarity_src_hyp).reshape(-1,1)).flatten(),name="cos_sim_src_hyp")



In [161]:
cos_df = pd.concat([cs_rh,cs_sr,cs_sh,df1.loc[:,"z-score"]],axis=1)
cos_df

cos_sim_ref_hyp  cos_sim_src_ref  cos_sim_src_hyp   z-score
0            -1.250038        -0.422368        -1.306007 -0.345024
1             1.048153         0.533522         0.774393  0.903800
2            -0.678580         0.130823         0.188789  0.700503
3            -0.987798         0.273078        -0.873894 -1.256572
4            -0.938938         0.782586        -1.083445  0.293909
...                ...              ...              ...       ...
21699         1.080071         1.100543         1.362532  1.246459
21700         1.183931        -0.374398         0.015242  0.792878
21701         0.670196         0.637920         0.668873  0.597068
21702         0.720476        -0.220658         0.773841 -0.305719
21703         1.140419         0.545205         1.244882  0.995212

[21704 rows x 4 columns]

In [162]:
# Pearson
print("Pairwise Pearson")
cos_df.corr()

Pairwise Pearson


cos_sim_ref_hyp  cos_sim_src_ref  cos_sim_src_hyp   z-score
cos_sim_ref_hyp         1.000000         0.618973         0.797330  0.316523
cos_sim_src_ref         0.618973         1.000000         0.692192  0.182758
cos_sim_src_hyp         0.797330         0.692192         1.000000  0.195875
z-score                 0.316523         0.182758         0.195875  1.000000

In [163]:
# Kendall
print("Pairwise Kendall")
cos_df.corr(method="kendall")

Pairwise Kendall


cos_sim_ref_hyp  cos_sim_src_ref  cos_sim_src_hyp   z-score
cos_sim_ref_hyp         1.000000         0.435721         0.608597  0.223125
cos_sim_src_ref         0.435721         1.000000         0.540446  0.118914
cos_sim_src_hyp         0.608597         0.540446         1.000000  0.130874
z-score                 0.223125         0.118914         0.130874  1.000000

In [164]:
# Spearman
print("Pairwise Spearman")
cos_df.corr(method="spearman")

Pairwise Spearman


cos_sim_ref_hyp  cos_sim_src_ref  cos_sim_src_hyp   z-score
cos_sim_ref_hyp         1.000000         0.604819         0.787616  0.326655
cos_sim_src_ref         0.604819         1.000000         0.723731  0.176150
cos_sim_src_hyp         0.787616         0.723731         1.000000  0.193575
z-score                 0.326655         0.176150         0.193575  1.000000

---
Linear Regression <br>to try and predict avg score based on the cos similarity 

In [165]:
X = cos_df.drop(columns='z-score')
y = cos_df['z-score']

In [166]:
lin_model = LinearRegression()

In [167]:
kf = KFold(n_splits = 10)
for train_index, test_index in kf.split(X):
    X_train, X_val = X.iloc[train_index], X.iloc[test_index]
    y_train, y_val = y.iloc[train_index], y.iloc[test_index]
    
    lin_model.fit(X_train,y_train)
    y_pred = lin_model.predict(X_val)
    print(mean_absolute_error(y_val,y_pred))

0.6527408819767678
0.6757954960873159
0.6668912096850256
0.6452570374362728
0.6109181224425928
0.6440656783167589
0.5899620045423257
0.6368125210787335
0.6355302938729582
0.6398936072186637


In [168]:
print(lin_model.coef_)
print(lin_model.intercept_)

[ 0.37602588  0.03522878 -0.16227454]
-0.004071303295636321


In [170]:
# A model with src_ref and src_hyp only. 
X = cos_df.drop(columns=['cos_sim_ref_hyp','z-score'])
y = cos_df['z-score']

In [171]:
kf = KFold(n_splits = 10)
for train_index, test_index in kf.split(X):
    X_train, X_val = X.iloc[train_index], X.iloc[test_index]
    y_train, y_val = y.iloc[train_index], y.iloc[test_index]
    
    lin_model.fit(X_train,y_train)
    y_pred = lin_model.predict(X_val)
    print(mean_absolute_error(y_val,y_pred))
print(lin_model.coef_)
print(lin_model.intercept_)

0.6872387987829903
0.7074090038492186
0.7017583072988852
0.6806976681436335
0.648423808347745
0.6688137843687497
0.6230586532258409
0.6679940901556314
0.6562495683670608
0.6630161471191572
[0.08666064 0.10156855]
-0.007630570925880059


Seems like it is about the same, which I guess does make sense, consdering the correlations between the three are likely to be very strong.

In [172]:
y_pred

array([-0.11235052, -0.2473391 ,  0.15787498, ...,  0.11558839,
        0.05184496,  0.16605814])

---
Using a Neural Network

In [180]:
MLP_model = MLPRegressor(hidden_layer_sizes=(2,2),max_iter=250,learning_rate_init=0.0015,solver="lbfgs")

In [181]:
# Train test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [182]:
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [183]:
kf = KFold(5)
for train_index, val_index in kf.split(X_train):
    kf_X_train, X_val = X_train[train_index], X_train[val_index]
    kf_y_train, y_val = y_train.iloc[train_index], y_train.iloc[val_index]    
    
    MLP_model.fit(kf_X_train,kf_y_train)
    y_val_pred = MLP_model.predict(X_val)
    print(f"Model loss: {MLP_model.loss_}")
    print(f"The MAE is {mean_absolute_error(y_val,y_val_pred)}")

Model loss: 0.34835343901739707
The MAE is 0.6626282494895644
Model loss: 0.34638616655853294
The MAE is 0.672010648802219
Model loss: 0.3488007211843734
The MAE is 0.6671417028880381
Model loss: 0.3498710466355067
The MAE is 0.6562765911072028
Model loss: 0.34362297586832613
The MAE is 0.6683375974555464


---
Using Neural Networks, directly on the embeddings.

In [ ]:
## Maybe don't run this if you care about time.

In [199]:
# An input has to be of shape (3,1024), because we have 3 embedded vectors of size 1024.
# combined array
full_arr = np.dstack((source_arr,refer_arr,trans_arr))

# Option 2, make it size (1,2048), by concatenating the arrays. This is what we are using now, according to teacher's indications.
full_arr_c = np.concatenate((refer_arr,trans_arr),axis=1)


In [200]:
X = full_arr_c.copy()
y = df1["z-score"].to_numpy()

# Train test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [201]:
X_train.shape

(19533, 2048)

In [249]:
model = models.Sequential()

model.add(layers.Dense(1024,activation="relu",input_dim=X_train.shape[1]))
model.add(layers.Dense(512,activation="relu"))
model.add(layers.Dense(128,activation="relu"))
model.add(layers.Dense(64,activation="relu"))
model.add(layers.Dense(1,activation="tanh"))
model.compile(optimizer=keras.optimizers.Adam(lr=0.001),loss="mse",metrics=["mae"])

In [250]:
model.summary()

Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_55 (Dense)             (None, 1024)              2098176   
_________________________________________________________________
dense_56 (Dense)             (None, 512)               524800    
_________________________________________________________________
dense_57 (Dense)             (None, 128)               65664     
_________________________________________________________________
dense_58 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_59 (Dense)             (None, 1)                 65        
Total params: 2,696,961
Trainable params: 2,696,961
Non-trainable params: 0
_________________________________________________________________


In [251]:
# Fit. Batch Size < > Learning Rate

model.fit(X_train,y_train,epochs=10,batch_size=128,verbose=1)
val_mse,val_mae = model.evaluate(X_test,y_test)
print(f"This is val MSE: {val_mse}.\nThis the MAE:{val_mae}")

Epoch 1/10
19533/19533 [==============================] - 6s 286us/step - loss: 0.7097 - mae: 0.6724
Epoch 2/10
19533/19533 [==============================] - 5s 277us/step - loss: 0.6735 - mae: 0.6510
Epoch 3/10
19533/19533 [==============================] - 5s 279us/step - loss: 0.6501 - mae: 0.6369
Epoch 4/10
19533/19533 [==============================] - 5s 276us/step - loss: 0.6281 - mae: 0.6248
Epoch 5/10
19533/19533 [==============================] - 5s 274us/step - loss: 0.6106 - mae: 0.6146
Epoch 6/10
19533/19533 [==============================] - 6s 282us/step - loss: 0.5865 - mae: 0.6001
Epoch 7/10
19533/19533 [==============================] - 5s 276us/step - loss: 0.5679 - mae: 0.5883
Epoch 8/10
19533/19533 [==============================] - 5s 277us/step - loss: 0.5561 - mae: 0.5815
Epoch 9/10
19533/19533 [==============================] - 5s 276us/step - loss: 0.5380 - mae: 0.5699
Epoch 10/10
2171/2171 [==============================] - 0s 125us/step
This is val MSE: 0.6

In [252]:
test = model.predict(X_test)

In [253]:
test

array([[ 0.25912875],
       [ 0.09689508],
       [-0.50694126],
       ...,
       [ 0.3891723 ],
       [ 0.18257554],
       [ 0.41995084]], dtype=float32)

In [254]:
df1["z-score"].corr(pd.Series(model.predict(X).flatten()))
# The results are much better, and indicative of a good metric.

0.5576136341607313